### ISSUE TITLE
simulation regex_error

### ISSUE THREAD

**Issue by pawel125** [cbg-ethz/SCICoNE#103]
Hi!

I am trying to test SCICoNE, but it fails during simulation with the following error:

> (scicone_env) [pkus@master1 build]$ ./simulation
> terminate called after throwing an instance of 'std::regex_error'
>   what():  regex_error
> Aborted

Can you help me?

Bet wishes,
Paweł

**Comment by pedrofale** [comment]
Dear Pawel,

It looks like your gcc version does not support regular expressions. Can you see if your gcc version is >= 5.2.0, as indicated in the SCICoNE requirements (in the repo's README.md)?

**Comment by pawel125** [comment]
Yes, it is.

> gcc --version
> gcc (GCC) 10.2.0

Although I am not sure if all other dependencies are linked properly. It is not easy to install all of this without root if you do not have much experience with Linux. After cmake I had the following output:

> cmake ..
> -- Could NOT find OpenMP_CXX (missing OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
> -- Could NOT find OpenMP (missing OpenMP_CXX_FOUND) (found version "3.1")
> -- Configuring done
> -- Generating done
> -- Build files have been written to

Can it point to any problem?

**Comment by pedrofale** [comment]
That's weird. I will have to test with GCC 10.2.0 to make sure it's working and get back to you. If possible, could you downgrade your GCC to e.g. 6.3.0? Our continuous integration tests are using whatever version is the default on the Ubuntu 16.04 package manager (i.e. we just run `apt-get update && apt-get install -y gcc g++`).

That `cmake` output just means you won't be able to parallelize some computations, which is unrelated to your problem. What's the output of `make`?

**Comment by pawel125** [comment]
This is the output of make:

> (base) [pkus@master1 build]$ make
> [ 18%] Built target tests
> [ 34%] Built target inference
> [ 51%] Built target simulation
> [ 67%] Built target score
> [ 83%] Built target save_root_per_nu
> [100%] Built target breakpoint_detection

I have installed gcc-6.3.0. This time everything was installed correctly (no problems with cmake or make), but still the same problem with ./simulation

**Comment by pedrofale** [comment]
That's odd! It may happen that when you compile you are using some other version, though. Could you do
```
cmake -DCMAKE_BUILD_TYPE=Debug ..
make VERBOSE=1
```
and post the logs here?

**Comment by pawel125** [comment]
It seems that you were right:

> (base) [master1 build]$ cmake -DCMAKE_BUILD_TYPE=Debug ..
> -- The C compiler identification is GNU 4.8.5
> -- The CXX compiler identification is GNU 4.8.5
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found OpenMP_C: -fopenmp (found version "3.1")
> -- Found OpenMP_CXX: -fopenmp (found version "3.1")
> -- Found OpenMP: TRUE (found version "3.1")
> -- Found Boost: /usr/include (found suitable version "1.53.0", minimum required is "1.47") found components: random -- Configuring done
> -- Generating done
> -- Build files have been written to: ~/programs/SCICoNE/build

But why does it happen and how to fix it?

[make_out.txt](https://github.com/cbg-ethz/SCICoNE/files/5262524/make_out.txt)

**Comment by pedrofale** [comment]
You probably have multiple installations of GCC and the one that is under `/usr/bin/` is pointing to 4.8.5. As suggested [here](https://stackoverflow.com/questions/28696054/cmake-find-wrong-gcc-version), try this:
```
cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ..
```

**Comment by pawel125** [comment]
Now it works, thanks!

**Comment by pedrofale** [comment]
Great! I hope you find SCICoNE useful.
