### ISSUE TITLE
error with breakpoint detection binary

### ISSUE THREAD

**Issue by jmfa** [cbg-ethz/SCICoNE#104]
Hey guys,

I'm trying to test my SCICoNE installation (following your tutorial) but I get an error using `detection_breakpoint`.
My installation didn't output any error so I'm not sure what's happening. 

Here's the error message:
```
$ ./breakpoint_detection --d_matrix_file ./10nodes_10regions_100000reads__d_mat.csv --n_bins 100 --n_cells 40 --window_size 10 --threshold 3.0 --bp_limit 300 --verbosity=1 --evaluate_peaks=True
 
min_cells is not specified, 4 cells are going to be considered
No LR file passed. Will compute new one.
Reading the input matrix: ./10nodes_10regions_100000reads__d_mat.csv
Input matrix is read.
breakpoint_detection: /usr/SCICoNE/SCICoNE/src/SignalProcessing.cpp:120: std::vector<_RealType> SignalProcessing::crop(std::vector<_RealType>&, int) [with T = double]: Assertion `signal.size() > offset*2' failed.
Aborted
```

Any idea of what might be causing this issue?
By the way, the input data matrix was generated using the provided `simulation` binary as follows:
 ```
$ ./simulation --n_cells 40 --n_bins 100 --n_regions 10 --n_nodes 10 --n_reads 100000 --ploidy 2 --verbosity 2  --seed 42 --print_precision 32
```
Thanks in advance!
J

**Comment by pedrofale** [comment]
Hi Joāo,

Thanks for pointing this out! I have pushed a fix. Please use the latest version and let us know if you find any other issues.

**Comment by jmfa** [comment]
Hi Pedro,
Thanks! Just compiled the new version and it works ;)

Cheers,
J
