### ISSUE TITLE
Errors compiling if Boost not installed in a standard location

### ISSUE THREAD

**Issue by soccin** [cbg-ethz/SCICoNE#106]
Our boost is installed in a non standard location but setting BOOST_ROOT would not work. Got compile errors on missing boost include files. Not a CMake expert but I got it to work by making the following change:

```{diff}
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 290c86a..2ba0c9b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -33,6 +33,7 @@ endif(OPENMP_FOUND)
 
 # Search for boost and nlopt
 find_package(Boost 1.47 COMPONENTS random REQUIRED)
+include_directories(${Boost_INCLUDE_DIRS})
 find_package(NLopt REQUIRED)
 include_directories(${NLOPT_INCLUDE_DIRS})
```

**Comment by pedrofale** [comment]
That's a good point that we forgot to deal with, thanks! Can you open a pull request to add this change in?

**Comment by soccin** [comment]
Yes, just created one. Thanks.

**Comment by pedrofale** [comment]
Thanks! #107 is merged.
