### ISSUE TITLE
detected breakpoints are not stored in bps['segmented_regions'].

### ISSUE THREAD

**Issue by wangyong98** [cbg-ethz/SCICoNE#111]
I followed your tutorial and was able to run through this step:
bps = sci.detect_breakpoints(sim['d_mat'], threshold=6.0)

Then I failed the next step: 
scicone.plotting.plot_matrix(sim['d_mat'], bps=bps['segmented_regions'], cbar_title='Raw counts', vmax=20)

Error messages:
KeyError                                  Traceback (most recent call last)
<ipython-input-31-5fa574445d94> in <module>
----> 1 scicone.plotting.plot_matrix(sim['d_mat'], bps=bps['segmented_regions'], cbar_title='Raw counts', vmax=20)

KeyError: 'segmented_regions'

Apparently, bps doesn't have the "segmented_regions" array.

**Comment by wangyong98** [comment]
I tried the 10X example and got the same error:
bps = sci.detect_breakpoints(data=sci.data['filtered_counts'][cell_subset], verbosity=1,
                            input_breakpoints=list(sci.data['filtered_chromosome_stops'].values()),
                            window_size=50)

Mapping to genes...
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-ea44baeec2fc> in <module>
----> 1 bps = sci.detect_breakpoints(data=sci.data['filtered_counts'][cell_subset], verbosity=1,
      2                             input_breakpoints=list(sci.data['filtered_chromosome_stops'].values()),
      3                             window_size=50)

/opt/conda/lib/python3.8/site-packages/scicone/scicone.py in detect_breakpoints(self, data, window_size, threshold, bp_limit, bp_min, lr, sp, evaluate_peaks, compute_lr, compute_sp, input_breakpoints, verbosity)
    268             print('Mapping to genes...')
    269             self.region_gene_map = utils.get_region_gene_map(self.data['bin_size'], self.data['unfiltered_chromosome_stops'],
--> 270                                     self.bps['segmented_regions'], self.data['excluded_bins'])
    271             print('Done.')
    272 

KeyError: 'segmented_regions'

**Comment by wangyong98** [comment]
i hate these shitty programs that are full of errors and don't provide any support

**Comment by pedrofale** [comment]
Hi @wangyong98, I am looking into this error.

**Comment by pedrofale** [comment]
Hi @wangyong98, this bug is now fixed. Can you please confirm that you can run everything?

**Comment by wangyong98** [comment]
Thanks, Pedro!

Let me try it. I will let you know if I have any questions. Thanks again!

Best regards,

Yong (Tony) Wang
