### ISSUE TITLE
cannot detect breakpoints with ./breakpoint_detection

### ISSUE THREAD

**Issue by sdangelis** [cbg-ethz/SCICoNE#112]
possibly related to #111 ./breakpoint_detection does not seem to detect any breakpoint from either real data or the output of a simulation with the default parameters with:

```./simulation --n_cells 400 --n_bins 1000 --n_regions 10 --n_nodes 10 --n_reads 100000 --ploidy 2 --verbosity 2  --seed 42 --print_precision 32```
```./breakpoint_detection --d_matrix_file ./10nodes_10regions_100000reads__d_mat.csv  --n_bins 1000 --n_cells 400 --window_size 10 --threshold 3.0 --bp_limit 300 --verbosity=1 --evaluate_peaks=True```

this is the output (verbosity = 1) 

![image](https://user-images.githubusercontent.com/60362523/108835935-19b2f680-75c8-11eb-97b0-576be9ebcd14.png)

It happens both in my Linux (gcc) and macOS (clang) installs passing build tests. First time raising an issue on here so let me know if you need more info

**Comment by soccin** [comment]
The following commit: `3af7d80cf506b8994` works so the problem seems to have been introduced after this commit.

**Comment by pedrofale** [comment]
Hi @sdangelis, I am sorry for the delay. We are back to working on SCICoNE. I have fixed this bug and pushed to the main branch. Can you please re-try with the latest version and see if it works for you?

**Comment by sdangelis** [comment]
Hi, Thank you for working on this. It seems I can now run the command line tutorial without problems.

**Comment by mjz1** [comment]
I have tried both the `master` branch and newer `rna` branch and am seeing this error in the `10x_example.ipynb` notebook at the `learn_tree` step:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 bps = sci.detect_breakpoints(data=sci.data['filtered_counts'][cell_subset], verbosity=2,
      2                             input_breakpoints=list(sci.data['filtered_chromosome_stops'].values()),
      3                             window_size=50)

File ~/miniconda3/lib/python3.8/site-packages/scicone/scicone.py:270, in SCICoNE.detect_breakpoints(self, data, window_size, threshold, bp_limit, bp_min, lr, sp, evaluate_peaks, compute_lr, compute_sp, input_breakpoints, smoothed, verbosity)
    267 if 'unfiltered_chromosome_stops' in self.data.keys():
    268     print('Mapping to genes...')
    269     self.region_gene_map = utils.get_region_gene_map(self.data['bin_size'], self.data['unfiltered_chromosome_stops'],
--> 270                             self.bps['segmented_regions'], self.data['excluded_bins'])
    271     print('Done.')
    273 return output

KeyError: 'segmented_regions'
```


And in the `tutorial.ipynb` at the `detect_breakpoints` step:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [10], in <cell line: 1>()
----> 1 inferred_tree = sci.learn_tree(sim['d_mat'], bps['segmented_region_sizes'], n_reps=4, seed=seed)

File ~/miniconda3/lib/python3.8/site-packages/scicone/scicone.py:427, in SCICoNE.learn_tree(self, data, segmented_region_sizes, n_reps, cluster, full, cluster_tree_n_iters, nu_tree_n_iters, full_tree_n_iters, max_tries, robustness_thr, min_cluster_size, **kwargs)
    425 # Expand clusters back into cells to get the cell per bin genotype
    426 cluster_bin_genotypes = tree.outputs['inferred_cnvs']
--> 427 cluster_node_ids = tree.outputs['cell_node_ids']
    429 cell_bin_genotypes = np.empty((segmented_data.shape[0], cluster_bin_genotypes.shape[1]))
    430 cell_node_ids = np.empty((segmented_data.shape[0], 1))

KeyError: 'cell_node_ids'
```
