### ISSUE TITLE
My h5 files are not compatible

### ISSUE THREAD

**Issue by Romeo1-1** [cbg-ethz/SCICoNE#118]
Hello,

Thank you for this package. I did all the "vignettes" without any issue, but when trying to use SCICoNE on my own h5 files i receive this error (screenshots joined). 

![Read1](https://user-images.githubusercontent.com/101837631/165560539-87f725b1-e904-4f83-a78c-0ab49eca32a5.JPG)

![Read2](https://user-images.githubusercontent.com/101837631/165560558-d4462438-0052-4ab9-82b5-4c6ab7044cd0.JPG)

I had the same problem with all my h5 files. My h5 files were aligned using Cell Ranger 1.1.0 using hg38 genome.

I ran the analysis on the same Jupyter Notebook as the 10x exemple to show my problem. But i received the same errors when running the script on Python 3.9.7 on Ubuntu via WSL2.

I checked those two h5 files on R using rhdf5, but i couldn't find any difference. And i couldn't find any answer on internet. My guess would be that maybe there is something going on because i used hg38 genome ? Do you have any idea ?

Thank you in advance,

**Comment by Romeo1-1** [comment]
Hello @pedrofale , i was able to find the problem : in my .H5 file, the chromosomes were named "chr1", "chr2" etc, while in the breast.H5, they were named "1", "2" etc. After manually renaming every "chrxxx" into "xxx", SCICONE is now able to process my H5 file !

I didn't got enough time to look thoroughly the code but i couldn't find an easy solution. Maybe you have an idea ?

I encountered another issue downstream. When running `sci.learn.tree`, in the end i get an error with cell.note.id . I would get the same error at the same point with the 10x example ipub with the breast.h5 file. I tried also to look at the code but coudln't find anything. I tried again after "updating" SCICoNE but i got the same error. I really don't understand this error, maybe you have an idea too ?

![image](https://user-images.githubusercontent.com/101837631/167042465-03f4640b-1acc-4cec-aa04-706c2f5a8427.png)

![image](https://user-images.githubusercontent.com/101837631/167042443-0c373c24-32e2-4f5b-84dd-8421eb041195.png)

Finally, i tried to make a clean new installation of SCICONE today, but was hit with this error when using `make` that i didn't have before. Maybe it's an error on my end tho.

![image](https://user-images.githubusercontent.com/101837631/167043541-89a3706f-5568-430c-92ea-c9832695b4bf.png)

Thank you again a lot for your package,

**Comment by pedrofale** [comment]
Hi @Romeo1-1,

1. Indeed the current SCICoNE python interface for 10X Genomics data expects chromosomes to be named without the "chr" prefix. Renaming as you did will work. Nevertheless, I have pushed a new version that takes care of that. You just need to pass the prefix of your choice to `read_10x`. By default, it still assumes there is no prefix, but you can now set the keyword argument `prefix`. In your case, simply do `read_10x(..., prefix='chr')`. Please download, re-install and give it a try!
 
2. I don't seem to be able to reproduce the error with the `cell_node_ids` key. Were you able to run the [tutorial](https://github.com/cbg-ethz/SCICoNE/blob/master/docs/notebooks/tutorial.ipynb) notebook?

3. Sorry for the latest change breaking the compilation! The latest version will compile with no problems.  

Best,
Pedro

**Comment by Romeo1-1** [comment]
Hello @pedrofale ,

Thank you for this update ! The compilation worked, i only get this error that repeated a few time but i was able to use the package anyway (i installed it again in a new directory just to showcase this error)

![image](https://user-images.githubusercontent.com/101837631/167478323-67639a05-37a9-473d-84a6-dbca3d1fc90d.png)

![image](https://user-images.githubusercontent.com/101837631/167478574-f20cda97-3c46-458f-95c0-f3439735f248.png)


1. Even with `sci.read_10x('cnv_data.h5', prefix = 'chr', downsampling_factor=10)` i would still get the same error. 

![image](https://user-images.githubusercontent.com/101837631/167467907-e83344cd-f538-446e-b863-e57dcb479982.png)
![image](https://user-images.githubusercontent.com/101837631/167467994-01e949fc-9c63-4a83-8db7-e4fca019a799.png)

I wasn't able to pinpoint exactly where the problem was, but after modifiyng every `prefix = none` or  `prefix = prefix`  in the "utils_10x.py" script with `prefix = "chr"` it now **works** !

Downstream, i had a few problems because the name of my chromosomes were different. With the breakpoint detection, i had to edit the "utils.py" script for it to work. On the screenshot i joined, i added "chr" to the lines i highlighted.

![image](https://user-images.githubusercontent.com/101837631/167457792-2937483e-3130-45f5-a178-a8bf4c7536b6.png)

- I also get this error now when running `chr_neutral_state`. On the "utils.py" i wasn't able to find a workaround. I don't get this one error when using my "renamed" .h5 files or the breast.h5 from the tutorial in a new environment

![image](https://user-images.githubusercontent.com/101837631/167460716-f6982b31-a9d2-4a33-b7d0-a6229b945366.png)

2. I still have the same problem with "cell_nodes_id". When i run the tutorial notebook with the breast file, i get the same error at the exact same point.

With my own data (and my modified scripts) :
![image](https://user-images.githubusercontent.com/101837631/167461916-707914f8-c422-4aa2-b536-08f19f3707d8.png)

With your tutorial notebook (on a new environnment with the update) :

![image](https://user-images.githubusercontent.com/101837631/167476929-a1e7996e-ef3c-41a4-80e8-d15c027096c5.png)
![image](https://user-images.githubusercontent.com/101837631/167476996-a9afc9c5-7199-49e4-929c-0fddee5e8512.png)

I have no idea why i get this issue and you don't. Maybe its because of the error i got when compiling ?

Thank you again a lot,
Rémi

**Comment by Romeo1-1** [comment]
Hello @pedrofale 

I'm sorry but i still got an error with read.10x. This time i was able to pinpoint the culprit. There were still a `prefix = none` in scicone.py, i highlighted the change i made & now the read.10x works !

![image](https://user-images.githubusercontent.com/101837631/167716205-6501cc0e-9dea-4ffb-8d95-5c3ce0a1ae42.png)

I also still got the errors with breakpoint ! I played around with the script, after modifying a little bit the scicone.py script, the utils.py and finally adding `prefix = "chr` as argument, it worked !

![image](https://user-images.githubusercontent.com/101837631/167741297-f7c7514b-bc56-4566-9189-805702df668f.png)

![image](https://user-images.githubusercontent.com/101837631/167742755-8d7f0515-c5b7-49df-b661-12685c08bcca.png)

![image](https://user-images.githubusercontent.com/101837631/167742695-796f33a1-6b3e-481e-96c2-02ae312c25f0.png)

As you can see, I also had to modify the ` bin_gene_region_df = pd.DataFrame(index=range(f"{prefix}{chr_stops['Y']}"+1))` Without this modification, i get this error (screenshot). Also i tried different combination/things with `prefix` but had no luck :

![image](https://user-images.githubusercontent.com/101837631/167742095-9799625b-0b5e-4872-a0e6-eceae59f2fb5.png)


Downstream, i still get this error (screenshot). I tried looking around in the script but couldn't find any easy answer. As i told you earlier, i don't get this one with the Tutorial Notebook

![image](https://user-images.githubusercontent.com/101837631/167743435-58e143d5-c191-4c8b-bfd9-f5070b132eb1.png)

And i still get the `cell_node_ids` error. I really don't know where it comes from. If you wish so i can send you my .h5 file ! It could be easier that way for you to identify the different problems.

Cheers and thank you again,

Rémi

**Comment by pedrofale** [comment]
Hi @Romeo1-1, thanks for providing me with your file! I have fixed both the chromosome naming and the `cell_node_ids` issues. Please re-install the newest version and let me know if it worked for you!

**Comment by pedrofale** [comment]
Hi Rémi, good to know it's mostly working. Can you show me exactly the complete code you're running (preferably as text instead of screenshots) so I can run it and understand why you get that KeyError?

**Comment by Romeo1-1** [comment]
Sorry, here's the code i've been running now. It's exactly the same as in the example notebook

`diploid_tree = sci.learn_tree(region_neutral_states=region_neutral_states,
                              cluster_tree_n_iters=40000,
                              cluster=True, full=False, n_reps=5, max_tries=4,
                              copy_number_limit=4, seed=seed)`

**Comment by pedrofale** [comment]
But you get the error with your own `cnv_data.h5` that you sent me, right? And you said you used different numbers of cells for the breakpoint detection. Can you please show me the complete notebook or script you're running so I can try to reproduce your error?

**Comment by Romeo1-1** [comment]
Yes exactly it's with my own datas ! That's what i ran 

```
import scicone
import numpy as np

install_path = './build/'
temporary_outpath = './'
seed = 42 # for reproducibility

np.random.seed(seed)

# Create SCICoNE object
sci = scicone.SCICoNE(install_path, temporary_outpath, verbose=False)

sci.read_10x('cnv_data.h5', prefix = 'chr', downsampling_factor=8)

normalized_counts = sci.data['filtered_counts'] / np.sum(np.abs(sci.data['filtered_counts']), axis=1).reshape(-1, 1)
normalized_counts *= normalized_counts.shape[1]

scicone.plotting.plot_matrix(normalized_counts, cbar_title='Normalized\n  counts',
                            chr_stops_dict=sci.data['filtered_chromosome_stops'], vmax=2,
                            cluster=True)

cell_subset = np.random.choice(842, size=100, replace=False)

bps = sci.detect_breakpoints(data=sci.data['filtered_counts'][cell_subset], verbosity=1, prefix = "chr",
                            input_breakpoints=list(sci.data['filtered_chromosome_stops'].values()),
                            window_size=50)

scicone.plotting.plot_matrix(normalized_counts, bps=bps['segmented_regions'],
                             chr_stops_dict=sci.data['filtered_chromosome_stops'],
                             cbar_title='Normalized\n  counts', vmax=2)

chr_neutral_states = dict(zip(sci.data['filtered_chromosome_stops'].keys(), 
                         [2] * len(sci.data['filtered_chromosome_stops'].keys())))
chr_neutral_states['X', 'Y'] = 1

region_neutral_states = scicone.utils.set_region_neutral_states(sci.bps['segmented_regions'], 
                                                                 list(sci.data['filtered_chromosome_stops'].values()), 
                                                                 list(chr_neutral_states.values()))

diploid_tree = sci.learn_tree(region_neutral_states=region_neutral_states,
                              cluster_tree_n_iters=40000,
                              cluster=True, full=False, n_reps=5, max_tries=4,
                              copy_number_limit=4, seed=seed)
```

**Comment by pedrofale** [comment]
It looks like this was a bug in dealing with the last chromosome! Since we had only tested this for female patients and we remove chromosome Y from the tree inference since it will always have 0 read counts, the fact that we weren't reading the last detected region correctly was never detected. I have pushed a fix. Please let me know if this works!

**Comment by Romeo1-1** [comment]
Hey @pedrofale, thank you a lot for the update and your reactivity, everything works perfectly fine for now !
