### ISSUE TITLE
Should n_nodes be 0 or 1 for an empty tree (with root only)?

### ISSUE THREAD

**Issue by anilbey** [cbg-ethz/SCICoNE#55]
Corner cases:
* event prior asserts `assert(n==static_cast<int>(p_v.size()));`
* `chi_insert_delete`: it gets INF when n=0

**Comment by pedrofale** [comment]
Is this relevant anymore?

**Comment by anilbey** [comment]
Ah yes this can be closed. It was a concern about whether this corner case was breaking the mcmc probabilities.
