### ISSUE TITLE
n_bins/n_reads options not parsed

### ISSUE THREAD

**Issue by ingenumich** [cbg-ethz/SCICoNE#97]
Installed and built with no issues, but use of the n_bins/n_reads options causes a 'does not exist' return; doesn't seem to be parsed via add_options()  (infer_test.cpp, breakpoint_detection.cpp, score_tree.cpp).  Maybe just missing a check-in?

Cool project btw..

**Comment by pedrofale** [comment]
Hi @ingenumich, could you show the full input and error messages, please? Thank you.

**Comment by ingenumich** [comment]
Info:  environment is Ubuntu 20.x (fresh install) running as a Hyper-V VM
(8GB memory, 8 virtual cores, 100GB SSD disk space).  Most packages were
installed via apt; nlopt was installed via Git (clone/build/install).

Output below, note the removal of options with each input.  Test matrix
file was supplied with same filename as your example:

---
faust@Ubu1:~$ cd SCICoNE/build
faust@Ubu1:~/SCICoNE/build$ ./inference --n_reads 100000 --print_precision
16 --n_nodes 10 --n_bins 10000 --n_iters 100 --n_cells 500 --verbosity 2
--ploidy 2 --seed 42 --postfix d31 --d_matrix_file ./30_d_mat.txt
--region_sizes_file ./30_region_sizes.txt
terminate called after throwing an instance of
'cxxopts::option_not_exists_exception'
  what():  Option ‘n_reads’ does not exist
Aborted (core dumped)
faust@Ubu1:~/SCICoNE/build$ ./inference --print_precision 16 --n_nodes 10
--n_bins 10000 --n_iters 100 --n_cells 500 --verbosity 2 --ploidy 2 --seed
42 --postfix d31 --d_matrix_file ./30_d_mat.txt --region_sizes_file
./30_region_sizes.txt
terminate called after throwing an instance of
'cxxopts::option_not_exists_exception'
  what():  Option ‘n_bins’ does not exist
Aborted (core dumped)
---

Cheers,
-Eric

**Comment by anilbey** [comment]
Hi @ingenumich, you are right. Those options do not exist anymore. The README.md file is not up-to-date. We will update it. 
In the meantime, here are the valid command line options you can use.
https://github.com/cbg-ethz/SCICoNE/blob/78e5b0c7dabd9cd462d5e70ee5a33bbaffc4c401/src/infer_trees.cpp#L85-L112

**Comment by pedrofale** [comment]
The `README.md` has been updated: 53f85d09182dc004936d1c0cadc5cac9ba176875. Let us know if you managed to use the program @ingenumich. Also note that we are currently working on a Python wrapper (see https://github.com/cbg-ethz/SCICoNE/tree/master/pyscicone) and will update the documentation soon.

**Comment by ingenumich** [comment]
Cloned the latest, looks good.  Thanks for the speedy replies and resolution!
Feedback:  a Python wrapper would be great, full Python usage would be welcome as well.  Understood why some languages/environments are chosen (I'm usually a C++/VS guy myself), but I'm shifting to Python/PyTorch/TF/etc despite some perf issues, so I can better support Ubuntu and Win10 environments.  Not being insulting or pushy, this is your sandbox, just friendly feedback.

**Comment by pedrofale** [comment]
Feedback is always welcome, of course -- especially at this stage. Thanks!
